import React, { useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import Home from "../components/Home";
import CommandLine from "../components/CommandLine";
import Projects from "../components/Projects";

export default function Index() {
  const [darkMode, setDarkMode] = useState(true);

  const sections = [
    { section: "HOME", color: "gradient-oceanic", link: "#" },
    { section: "PROJETOS", color: "gradient-hyper", link: "#" },
    { section: "HABILIDADES", color: "gradient-sunset", link: "#" },
    { section: "SOBRE", color: "gradient-mojave", link: "#" },
    { section: "CONTATO", color: "gradient-candy", link: "#" },
  ];

  return (
    <div className={`${darkMode ? "dark-theme" : "light-theme"} bg-primary`}>
      <Head>
        <title>Fabio Lima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        darkMode={darkMode}
        setDarkMode={setDarkMode}
        sections={sections}
      />
      <main className="m-auto h-full w-full max-w-screen-xl bg-primary">
        <Home />
        <CommandLine />
        <Projects />
      </main>
    </div>
  );
}
