import React, { useState } from "react";
import Head from "next/head";
import Header from "../components/sections/Header";
import Home from "../components/sections/Home";
import About from "../components/sections/About";
import Projects from "../components/sections/Projects";
import Contact from "../components/sections/Contact";
import CommandLine from "../components/CommandLine";

export default function Index() {
  const [darkMode, setDarkMode] = useState(true);

  const sections = {
    home: {
      title: "Fabio Lima.",
      nav: "HOME",
      color: "gradient-oceanic",
      id: "home",
    },
    about: {
      title: "Sobre.",
      nav: "SOBRE",
      color: "gradient-sunset",
      id: "sobre",
    },
    projects: {
      title: "Projetos.",
      nav: "PROJETOS",
      color: "gradient-hyper",
      id: "projetos",
    },
    contact: {
      title: "Contato.",
      nav: "CONTATO",
      color: "gradient-candy",
      id: "contato",
    },
  };

  const reveal = {
    initial: {
      opacity: 0,
      y: 30,
    },
    animate: (i) => ({
      opacity: 1,
      y: 0,
      transition: { type: "tween", delay: i * 0.1 },
    }),
  };

  return (
    <div
      className={`${
        darkMode ? "dark-theme" : "light-theme"
      } box-border flex min-w-[300px] flex-col items-center bg-primary px-5 text-secondary xs:px-10 md:px-20`}
    >
      <Head>
        <title>Fabio Lima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        darkMode={darkMode}
        setDarkMode={setDarkMode}
        sections={sections}
      />
      <main className="w-full max-w-screen-lg">
        <Home section={sections.home} reveal={reveal} />
        <About section={sections.about} reveal={reveal} />
        <Projects section={sections.projects} />
        <Contact section={sections.contact} />
        <CommandLine />
      </main>
    </div>
  );
}
